In [3]:
import pw2py as pw

### How to create an atomgeo object

In [23]:
# create an 'atomgeo' object from a qe file (can also read vasp, xyz, xsf, jdftx)
filename = '../relax.out'
geo = pw.atomgeo.from_file(filename)

### Attributes of the atomgeo object

In [24]:
# print some things about the geometry
print('-'*20, 'geo.ion', '-'*20)
print(geo.ion)          # ion names
print('-'*20, 'geo.pos_units', '-'*20)
print(geo.pos_units)    # units for the positions (crystal, angstrom, and bohr are supported)
print('-'*20, 'geo.pos', '-'*20)
print(geo.pos)          # xyz positions
print('-'*20, 'geo.par_units', '-'*20)
print(geo.par_units)    # units for the cell parameters (ibrav supported!)
print('-'*20, 'geo.par', '-'*20)
print(geo.par)          # cell parameters

-------------------- geo.ion --------------------
['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O'
 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2'
 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O'
 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2'
 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O'
 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2'
 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O'
 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Sn' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Sn']
-------------------- geo.pos_units --------------------
crystal
-------------------- geo.pos --------------------
[[ 3.18706896e-01  3.32943840e-01  9.17294076e-01]
 [ 1.64760445e-01  4.85266868e-01  9.17896614e-01]
 [ 4.85618459e-01  3.18969865e-01  8.27040790e-02]
 [ 3.33001365e-01  1.39489770e-02  8.31115030e-02]
 [ 1.80747575e-01  1.66387832e-01  8.33111260e-02

### Some cool things you can do

In [25]:
# convert positions to angstrom
geo.pos_units = 'angstrom'
print(geo.pos)

[[ 1.56272121e+00  2.95984328e+00  1.28340756e+01]
 [-7.99381158e-01  4.31398244e+00  1.28425059e+01]
 [ 3.34782316e+00  2.83561580e+00  1.15713208e+00]
 [ 3.34672838e+00  1.24005255e-01  1.16283244e+00]
 [ 1.00140701e+00  1.47917411e+00  1.16562542e+00]
 [-7.85779010e-01  1.59865239e+00  1.28308263e+01]
 [ 1.59072070e+00  1.08128423e-02  3.49811671e+00]
 [-8.04258624e-01  1.32907373e+00  3.49059311e+00]
 [ 7.32874024e-01  4.31894978e+00  5.83257644e+00]
 [ 7.72428153e-01  1.60269112e+00  5.81763770e+00]
 [-1.56538860e+00  2.98616546e+00  5.81812558e+00]
 [ 1.74369269e+00  3.06696615e+00  3.49566303e+00]
 [ 4.12731463e+00  1.48436306e+00  8.17803066e+00]
 [ 1.76765371e+00  2.77720026e+00  8.14998571e+00]
 [ 7.83054326e-01  1.35457463e+00  1.05084892e+01]
 [-1.78692989e+00  3.09071314e+00  1.05101802e+01]
 [ 3.56196828e+00  1.25537193e-03  1.05052158e+01]
 [ 1.77871005e+00  1.18852597e-01  8.17335447e+00]
 [-4.95088109e-03  2.94942186e+00  2.88585099e-01]
 [ 9.83239580e-03 -1.30124123e-

In [26]:
# replace all instances of Sn with Zr
geo.replace_ion('Sn', 'Zr')
print(geo.ion)

['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O'
 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2'
 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O'
 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2'
 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O'
 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2'
 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O'
 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Zr' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Zr']


In [27]:
# Build supercell
P=(3,3,1)
geo.build_supercell(P)
print(geo.ion)

['O' 'O' 'O' ... 'Fe2' 'Fe1' 'Zr']


In [28]:
# calculate 20 nearest neighbors of atom120 (careful python is base 0 so input 119)
df = geo.nearest_neighbor(119, return_type='df', N=20, include_site=True)
df.to_csv('neighbors.csv')  # write to csv file
print(df.iloc[1:7]) # print the first 6 nearest neighbors bonded to atom120

    ion                                                pos      dist
72    O  [1.496766860729326, 5.962536767395871, 8.13244...  2.025707
167   O  [1.7468664668390597, 9.078003132426542, 8.1718...  2.050021
103   O  [4.388096816781683, 7.28948457470863, 8.169695...  2.053180
98    O  [3.367355832767525, 8.843155158253232, 5.87709...  2.119019
99    O  [3.4162941278113057, 6.075095987137629, 5.8396...  2.138266
100   O  [0.9491220873952049, 7.391810610372396, 5.8384...  2.140088


In [29]:
geo.mass

<bound method mass of atomgeo(ion = array(['O', 'O', 'O', ..., 'Fe2', 'Fe1', 'Zr'], dtype=object),par = array([[ 30.79557505,   0.        ,   0.        ],
       [-15.39778752,  26.66975261,   0.        ],
       [  0.        ,   0.        ,  13.99123349]]),pos = array([[ 1.56272121,  2.95984328, 12.8340756 ],
       [-0.79938116,  4.31398244, 12.84250585],
       [ 3.34782316,  2.8356158 ,  1.15713208],
       ...,
       [12.83351107, 25.18225897, 11.37386487],
       [12.80779693, 22.19968429,  9.03248356],
       [12.82613161, 25.22028963,  7.24543561]]),par_units = 'angstrom',pos_units = 'angstrom')>

### Write the geo to a new file

In [30]:
# write some new file formats (will use extension but you can also use the ftype keyword)
geo.write_file('3x3x1.vasp')
geo.write_file('3x3x1.xsf')
geo.write_file('3x3x1.in',ftype='qeinp')

### Read the help menu

In [10]:
help(geo)

Help on atomgeo in module pw2py.atomgeo object:

class atomgeo(builtins.object)
 |  atomgeo(ion=None, par=None, pos=None, par_units=None, pos_units=None)
 |  
 |  class for atomic geometry
 |  
 |  Suggested to make object from file:
 |  -----
 |  geo = atomgeo.from_file(filename, ftype='auto')
 |  
 |  Attributes:
 |  -----
 |  
 |  par (np.array, float, shape = (3,3))
 |      - cell parameters
 |  
 |  par_units (str)
 |      - units of par, acceptable values include 'angstrom', 'bohr', 'alat'
 |  
 |  nat (int)
 |      - number of atoms
 |  
 |  ion (list, str)
 |      - list of atom/ion names (QE format)
 |  
 |  pos (np.array, float, shape = (nat, 3))
 |      - atomic positions
 |  
 |  pos_units (str)
 |      - units of pos, acceptable values include 'angstrom', 'bohr', 'crystal', 'alat'
 |  
 |  Methods defined here:
 |  
 |  __init__(self, ion=None, par=None, pos=None, par_units=None, pos_units=None)
 |      initialize atomgeo instance
 |  
 |  __repr__(self)
 |      define ato