In [11]:
import pw2py as pw

### How to create a qeinp object

In [12]:
# create an 'qeinp' object from a qe file
# specifying the prefix of the file will cause the code to check for both an input and output file (reading geo from output)
filename = 'relax'
inp = pw.qeinp.from_file(filename)

### Attributes of the qeinp object

In [13]:
# qeinp is a subclass of atomgeo so everything we can do with atomgeo we can do with qeinp
print('-'*20, 'inp.ion', '-'*20)
print(inp.ion)          # ion names
print('-'*20, 'inp.pos_units', '-'*20)
print(inp.pos_units)    # units for the positions (crystal, angstrom, and bohr are supported)
print('-'*20, 'inp.pos', '-'*20)
print(inp.pos)          # xyz positions
print('-'*20, 'inp.par_units', '-'*20)
print(inp.par_units)    # units for the cell parameters (ibrav supported!)
print('-'*20, 'inp.par', '-'*20)
print(inp.par)          # cell parameters

-------------------- inp.ion --------------------
['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O'
 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2'
 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O'
 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2'
 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O'
 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2'
 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O'
 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Sn' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Fe2' 'Fe1' 'Sn']
-------------------- inp.pos_units --------------------
crystal
-------------------- inp.pos --------------------
[[ 3.18706896e-01  3.32943840e-01  9.17294076e-01]
 [ 1.64760445e-01  4.85266868e-01  9.17896614e-01]
 [ 4.85618459e-01  3.18969865e-01  8.27040790e-02]
 [ 3.33001365e-01  1.39489770e-02  8.31115030e-02]
 [ 1.80747575e-01  1.66387832e-01  8.33111260e-02

### QE namelist

In [14]:
# but now we have information of the qe namelist!
print(inp.nml)  # namelists include control, system, electrons, etc.

&control
    calculation = 'relax'
    prefix = 'fe2o3'
    wf_collect = .true.
/

&system
    ibrav = 0
    nat = 120
    ntyp = 4
    ecutwfc = 40.0
    ecutrho = 240.0
    occupations = 'smearing'
    smearing = 'mp'
    degauss = 0.005
    nspin = 2
    starting_magnetization(2:3) = -0.5, 0.5
    lda_plus_u = .true.
    hubbard_u(2:3) = 4.3, 4.3
/

&electrons
    mixing_beta = 0.3
    conv_thr = 1e-07
    electron_maxstep = 200
/

&ions
/


In [15]:
# the easiest way to access the keys of the namelist is like this:
print(inp.nml.ibrav)
print(inp.nml.mixing_beta)

# but you can also do this
print(inp.nml['system']['ibrav'])
print(inp.nml['electrons']['mixing_beta'])

0
0.3
0
0.3


In [16]:
# let's make an nscf calculation
inp.nml.calculation = 'nscf'
inp.nml.nbnd = 1000
inp.kpt = [[4, 4, 4], [0, 0, 0]]

# and write the file
inp.write_file('nscf.in')

### QE Cards

In [17]:
# let's refresh things
inp = pw.qeinp.from_file(filename)

In [18]:
# we can also see all the cards of the input file
print(inp.card)  # cards include ATOMIC_POSITIONS, ATOMIC_SPECIES, K_POINTS, etc.
print(inp.card.ATOMIC_SPECIES)

{'CELL_PARAMETERS': 'angstrom', 'ATOMIC_SPECIES': {'O': [1.0, 'o_pbe_v1.2.uspp.F.UPF'], 'Fe1': [1.0, 'fe_pbe_v1.5.uspp.F.UPF'], 'Fe2': [1.0, 'fe_pbe_v1.5.uspp.F.UPF'], 'Sn': [1.0, 'sn_pbe_v1.4.uspp.F.UPF']}, 'K_POINTS': 'automatic', 'ATOMIC_POSITIONS': 'crystal'}
{'O': [1.0, 'o_pbe_v1.2.uspp.F.UPF'], 'Fe1': [1.0, 'fe_pbe_v1.5.uspp.F.UPF'], 'Fe2': [1.0, 'fe_pbe_v1.5.uspp.F.UPF'], 'Sn': [1.0, 'sn_pbe_v1.4.uspp.F.UPF']}


In [19]:
# if we replace all instances of Sn with Zr
inp.replace_ion('Sn', 'Zr')
# the ATOMIC_SPECIES will updated automatically!
print(inp.card.ATOMIC_SPECIES)

KeyError: 'ESPRESSO_PSEUDO'

In [20]:
# print our full input file
print(inp)

# save to a new input file
inp.write_file('zr.in')

&control
    calculation = 'relax'
    prefix = 'fe2o3'
    wf_collect = .true.
/

&system
    ibrav = 0
    nat = 120
    ntyp = 4
    ecutwfc = 40.0
    ecutrho = 240.0
    occupations = 'smearing'
    smearing = 'mp'
    degauss = 0.005
    nspin = 2
    starting_magnetization(2:3) = -0.5, 0.5
    lda_plus_u = .true.
    hubbard_u(2:3) = 4.3, 4.3
/

&electrons
    mixing_beta = 0.3
    conv_thr = 1e-07
    electron_maxstep = 200
/

&ions
/

ATOMIC_SPECIES
    O        1.0000  o_pbe_v1.2.uspp.F.UPF
    Fe1      1.0000  fe_pbe_v1.5.uspp.F.UPF
    Fe2      1.0000  fe_pbe_v1.5.uspp.F.UPF
    Sn       1.0000  sn_pbe_v1.4.uspp.F.UPF

CELL_PARAMETERS angstrom
        10.265191682       0.000000000       0.000000000
        -5.132595840       8.889917538       0.000000000
         0.000000000       0.000000000      13.991233495

ATOMIC_POSITIONS crystal
    O           0.318706896       0.332943840       0.917294076
    O           0.164760445       0.485266868       0.917896614
    O      

### Read the help menu

In [21]:
help(inp)

Help on qeinp in module pw2py.qeinp object:

class qeinp(pw2py.atomgeo.atomgeo)
 |  qeinp(nml, card, ion, par, par_units, pos, pos_units, if_pos, kpt)
 |  
 |  class for quantum espresso input file
 |      qedict = dictionary of namelists (nml), ATOMIC_SPECIES, CELL_PARAMETERS, ATOMIC_POSITIONS, and K_POINTS
 |      par = CELL_PARAMETERS data
 |      ion = ATOMIC_POSITIONS ions data
 |      pos = ATOMIC_POSITIONS position data
 |      if_pos = ATOMIC_POSITIONS if_pos data
 |      kpt = K_POINTS data
 |  
 |  Method resolution order:
 |      qeinp
 |      pw2py.atomgeo.atomgeo
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, nml, card, ion, par, par_units, pos, pos_units, if_pos, kpt)
 |      initialize qeinp object
 |  
 |  __repr__(self)
 |  
 |  __str__(self)
 |  
 |  add_atom(self, atoms, if_pos=[1, 1, 1])
 |      append atoms to self.ion and self.pos
 |      atoms = ion, pos
 |      
 |      calls atomgeo.add_atom(self, atoms)
 |  
 |  build_supercell(